spring:

dubbo:
  protocol:
    name: dubbo
    port: 8081
  registry:
    address: N/A

hmily:
  support:
    rpc:
      annotation: true

mybatis:
  type-aliases-package: pers.qingxuan.dubbo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true