spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/micro_mall?useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
    retinue:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/micro_mall_r1?useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
