/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pers.qingxuan.gateway;

import pers.qingxuan.gateway.server.HttpGatewayServer;

public class Application {
    public final static String GATEWAY_NAME = "NIOGateway";
    public final static String GATEWAY_VERSION = "1.0.0";

    public static void main(String[] args) throws InterruptedException {
        HttpGatewayServer server = new HttpGatewayServer(8080);
        server.start();
    }
}
